# ---------------------------------------------- #
#                Labels by purpose               #
# ---------------------------------------------- #

source:
  - changed-files:
      - any-glob-to-any-file:
          - install
          - uninstall
          - config/**/*

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*
          - pytest.ini

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - package*.json
          - requirements.txt

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

chore:
  - changed-files:
      - any-glob-to-any-file:
          - .devcontainer
          - .editorconfig
          - .gitignore
          - .hadolint*
          - .husky/**/*
          - .markdownlint*
          - .npmrc
          - .prettier*
          - .vscode/**/*
          - scripts/**/*
          - run
          - LICENSE

# ---------------------------------------------- #
#         Labels by technology / language        #
# ---------------------------------------------- #

docker:
  - changed-files:
      - any-glob-to-any-file:
          - .dockerignore
          - docker-compose*.yml
          - Dockerfile*

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*

python:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.py"

shellscript:
  - changed-files:
      - any-glob-to-any-file:
          - install
          - uninstall
          - pre-commit
          - run
          - "**/*.sh"

vscode:
  - changed-files:
      - any-glob-to-any-file:
          - .vscode/**/*
