version: "3.9"

services:
  app:
    build:
      context: .
      target: base
    image: aifrak/dotfiles:latest
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules

volumes:
  app-node-modules:
